### ISSUE TITLE
A10 on stable Rust

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Thomasdezeeuw/a10#63]
Below is a list of nightly features used in order of (roughly) to-be-solved-first to to-be-solved-last/easiest-to-solve-now, in other words the ones at the top are harder to solve so start with those (no point in losing functionality if we're still on nightly for another feature).

 * [ ] [`slice_ptr_get`](https://github.com/rust-lang/rust/issues/74265): used in various places.
 * [ ] [`ptr_sub_ptr`](https://github.com/rust-lang/rust/issues/95892): only used in `ReadBuf::release`.
 * [ ] [`maybe_uninit_array_assume_init`](https://github.com/rust-lang/rust/issues/96097): used in the `BufMutSlice` implementation for arrays and tuples.
 * [ ] [`maybe_uninit_uninit_array`](https://github.com/rust-lang/rust/issues/96097): used in the `BufMutSlice` implementation for arrays and tuples.
 * [ ] [`io_error_more`](https://github.com/rust-lang/rust/issues/): used in the `From<QueueFull>` impl for `QueueFull`, could use `io::ErrorKind::Other` for the time being.
 * [ ] [`async_iterator`](https://github.com/rust-lang/rust/issues/79024): used in multishot futures, could be replaced with a separate `poll_next` method.
 * [ ] [`new_uninit`](https://github.com/rust-lang/rust/issues/63291): used in a couple of `Futures`, could use `Box::new(MaybeUninit::new())`, although I think that's less efficient.
 * [ ] [`const_cmp`](https://github.com/rust-lang/rust/issues/92391): only used in `Config::with_idle_timeout`, could be made non-`const`.
 * [ ] [`const_mut_refs`](https://github.com/rust-lang/rust/issues/57349): used in `Submission::set_user_data` and `Submission::set_buffer_select`, could be made non-`const`.
 * [ ] [`mutex_unlock`](https://github.com/rust-lang/rust/issues/81872): used in `SubmissionQueue::add_no_result` and `ReadBuf::release`, can easily be replaced with a call to `drop` (and maybe a comment).
